In [4]:
a= [9,8,6,4,0]

In [30]:
x=7
type(x)

int

In [6]:
type(a)

list

In [7]:
#Array

In [8]:
#Install the library
#Import the library

In [9]:
import numpy as np

In [10]:
!pip install numpy

In [12]:
a1=np.array([9,8,6,4,0])
a1

array([9, 8, 6, 4, 0])

In [13]:
a1

array([9, 8, 6, 4, 0])

In [14]:
print(a1)

[9 8 6 4 0]


In [312]:
type(a1)

numpy.ndarray

In [15]:
a2=np.array([[1,2,3],[5,6,7]])

In [16]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [17]:
print(a2)

[[1 2 3]
 [5 6 7]]


In [18]:
a3=np.array([[1,2,3,5,6,7]])

In [19]:
a3

array([[1, 2, 3, 5, 6, 7]])

In [20]:
# ndim  : no of dimensions
# size  : no of elements
# dtype : datatype
# shape :

In [22]:
a1

array([9, 8, 6, 4, 0])

In [21]:
a1.ndim 

1

In [26]:
a1.size

5

In [29]:
a1.dtype

dtype('int32')

In [33]:
a1.shape

(5,)

In [23]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [34]:
a2.shape

(2, 3)

In [24]:
a2.ndim

2

In [25]:
a3.ndim

2

In [27]:
a2.size

6

In [28]:
a3.size

6

In [31]:
a2.dtype

dtype('int32')

In [32]:
a3.dtype

dtype('int32')

In [35]:
a3.shape

(1, 6)

In [36]:
a3

array([[1, 2, 3, 5, 6, 7]])

In [37]:
np.array([[1,2,3,4],[5,6,7]])

C:\Users\Ameer\AppData\Local\Temp/ipykernel_9720/110033056.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,2,3,4],[5,6,7]])


array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [40]:
type(a1)

numpy.ndarray

In [41]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [42]:
a2.shape

(2, 3)

In [43]:
a2.reshape(3,2)

array([[1, 2],
       [3, 5],
       [6, 7]])

In [44]:
a2.reshape(4,5)

ValueError: cannot reshape array of size 6 into shape (4,5)

In [45]:
a2.reshape(6,1)

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7]])

In [46]:
a2.reshape(1,6)

array([[1, 2, 3, 5, 6, 7]])

In [47]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [48]:
a2.reshape(6,)

array([1, 2, 3, 5, 6, 7])

In [49]:
a2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [5]],

       [[6],
        [7]]])

In [50]:
a2.reshape(3,1,2)

array([[[1, 2]],

       [[3, 5]],

       [[6, 7]]])

In [52]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[5],
        [6],
        [7]]])

In [53]:
a2.reshape(2,1,3)

array([[[1, 2, 3]],

       [[5, 6, 7]]])

In [54]:
#Task
#Create a 1D array of 12 elements. and then try to reshape to all the different possibilities of 1D and 2D

In [57]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
arr1.shape

(12,)

In [59]:
arr1.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [60]:
arr1.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [61]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [62]:
arr1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [63]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
#random method in numpy

In [89]:
np.random.rand(5,2)

array([[0.82426829, 0.69377305],
       [0.92902621, 0.08633273],
       [0.19120778, 0.73905017],
       [0.73121397, 0.62434898],
       [0.66610623, 0.90317862]])

In [148]:
np.random.randint(20,100,8)

array([77, 93, 43, 73, 27, 37, 46, 58])

In [149]:
np.random.randint(20,40,20)

array([24, 25, 29, 29, 33, 29, 37, 37, 30, 22, 38, 28, 20, 32, 35, 33, 24,
       30, 37, 33])

In [150]:
np.random.randint(20,40,20).reshape(4,5)

array([[25, 30, 24, 32, 38],
       [23, 23, 30, 26, 36],
       [38, 28, 22, 38, 20],
       [20, 39, 21, 31, 31]])

In [199]:
np.random.seed(7)
np.random.randint(20,40,(4,5))

array([[35, 24, 23, 39, 27],
       [34, 28, 34, 30, 28],
       [27, 26, 24, 36, 27],
       [32, 20, 31, 26, 39]])

In [183]:
print(np.random.randint(0,10,6))

[8 8 2 7 5 9]


In [200]:
speed=[100,150,180]
time=[1,1.5,3.3]

In [201]:
dist=speed*time

TypeError: can't multiply sequence by non-int of type 'list'

In [202]:
speed=np.array([100,150,180])
time=np.array([1,1.5,3.3])

In [203]:
dist=speed*time
dist

array([100., 225., 594.])

In [206]:
np.random.seed(4)
arr2=np.random.randint(20,40,20)
arr2

array([34, 25, 21, 28, 28, 38, 29, 27, 33, 28, 24, 38, 32, 26, 30, 23, 20,
       29, 26, 26])

In [205]:
#aggregate functions

In [207]:
np.sum(arr2)

565

In [209]:
arr2.sum()

565

In [210]:
arr2.size

20

In [211]:
np.size(arr2)

20

In [212]:
np.min(arr2)

20

In [213]:
np.max(arr2)

38

In [214]:
np.mean(arr2)

28.25

In [215]:
np.median(arr2)

28.0

In [219]:
np.argmax(arr2)

5

In [220]:
np.argmin(arr2)

16

In [226]:
np.product(arr2)

-1652555776

In [228]:
np.prod(arr2)

-1652555776

In [227]:
arr2

array([34, 25, 21, 28, 28, 38, 29, 27, 33, 28, 24, 38, 32, 26, 30, 23, 20,
       29, 26, 26])

In [229]:
np.sort(arr2)

array([20, 21, 23, 24, 25, 26, 26, 26, 27, 28, 28, 28, 29, 29, 30, 32, 33,
       34, 38, 38])

In [230]:
np.flip(arr2)

array([26, 26, 29, 20, 23, 30, 26, 32, 38, 24, 28, 33, 27, 29, 38, 28, 28,
       21, 25, 34])

In [235]:
np.flip(np.sort(arr2))

array([38, 38, 34, 33, 32, 30, 29, 29, 28, 28, 28, 27, 26, 26, 26, 25, 24,
       23, 21, 20])

In [236]:
for i in range(2,17,4):
    print(i)

2
6
10
14


In [237]:
np.arange(2,17,4)

array([ 2,  6, 10, 14])

In [238]:
3,7,11,15
np.arange(3,16,4)

array([ 3,  7, 11, 15])

In [241]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [243]:
np.random.seed(13)
arr5=np.random.randint(0,10,15)
arr5

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2, 6, 5, 9, 4, 2])

In [244]:
np.unique(arr5)

array([0, 2, 3, 4, 5, 6, 9])

In [245]:
np.unique(arr5,return_counts=True)

(array([0, 2, 3, 4, 5, 6, 9]), array([2, 4, 1, 3, 1, 2, 2], dtype=int64))

In [248]:
np.unique(arr5,return_index=True)

(array([0, 2, 3, 4, 5, 6, 9]),
 array([ 1,  0,  7,  5, 11,  3,  6], dtype=int64))

In [250]:
arr6=np.sort(arr5)
arr6

array([0, 0, 2, 2, 2, 2, 3, 4, 4, 4, 5, 6, 6, 9, 9])

In [256]:
np.power(arr6,0.5)

array([0.        , 0.        , 1.41421356, 1.41421356, 1.41421356,
       1.41421356, 1.73205081, 2.        , 2.        , 2.        ,
       2.23606798, 2.44948974, 2.44948974, 3.        , 3.        ])

In [257]:
np.sqrt(arr6)

array([0.        , 0.        , 1.41421356, 1.41421356, 1.41421356,
       1.41421356, 1.73205081, 2.        , 2.        , 2.        ,
       2.23606798, 2.44948974, 2.44948974, 3.        , 3.        ])

In [259]:
np.reciprocal(arr5)

C:\Users\Ameer\AppData\Local\Temp/ipykernel_9720/2244550815.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(arr5)
C:\Users\Ameer\AppData\Local\Temp/ipykernel_9720/2244550815.py:1: RuntimeWarning: invalid value encountered in reciprocal
  np.reciprocal(arr5)


array([          0, -2147483648, -2147483648,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0],
      dtype=int32)

In [263]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [265]:
np.reciprocal(a2,dtype='float')

array([[1.        , 0.5       , 0.33333333],
       [0.2       , 0.16666667, 0.14285714]])

In [266]:
arr5

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2, 6, 5, 9, 4, 2])

In [271]:
np.append(arr5,6)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2, 6, 5, 9, 4, 2, 6, 6])

In [269]:
arr5

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2, 6, 5, 9, 4, 2])

In [272]:
np.insert(arr5,2,7)

array([2, 0, 7, 0, 6, 2, 4, 9, 3, 4, 2, 6, 5, 9, 4, 2, 6])

In [273]:
x=np.array([2,4,5])
y=np.array([7,6,3])

In [280]:
np.add(x,y)

array([ 9, 10,  8])

In [274]:
x+y

array([ 9, 10,  8])

In [283]:
np.subtract(x,y)

array([-5, -2,  2])

In [275]:
x-y

array([-5, -2,  2])

In [285]:
np.multiply(x,y)

array([14, 24, 15])

In [276]:
x*y

array([14, 24, 15])

In [286]:
np.divide(x,y)

array([0.28571429, 0.66666667, 1.66666667])

In [277]:
x/y

array([0.28571429, 0.66666667, 1.66666667])

In [278]:
x//y

array([0, 0, 1], dtype=int32)

In [279]:
x%y

array([2, 4, 2], dtype=int32)

In [287]:
x*5

array([10, 20, 25])

In [290]:
#Conditions in numpy
np.random.seed(9)
c=np.random.randint(0,100,10)

In [291]:
c

array([92, 54, 56, 22, 65, 22, 52, 59, 40, 91])

In [292]:
c>50

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True])

In [293]:
c[c>50]

array([92, 54, 56, 65, 52, 59, 91])

In [294]:
c[c%2==0]

array([92, 54, 56, 22, 22, 52, 40])

In [299]:
np.where(c>50)

(array([0, 1, 2, 4, 6, 7, 9], dtype=int64),)

In [296]:
np.where(c%2==0)

(array([0, 1, 2, 3, 5, 6, 8], dtype=int64),)

In [300]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [301]:
np.zeros(4)

array([0., 0., 0., 0.])

In [303]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [304]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [305]:
np.ones([4,5])*255

array([[255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.]])

In [307]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [310]:
np.eye(4,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [311]:
np.eye(4,5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [314]:
mat1=np.matrix("1,2,3;4,5,6;7,8,9")
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [316]:
type(mat1)

numpy.matrix

In [318]:
mat2=np.matrix("5,4,6;7,8,3;1,9,2")
mat2

matrix([[5, 4, 6],
        [7, 8, 3],
        [1, 9, 2]])

In [315]:
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [319]:
np.inner(mat1,mat2)

matrix([[ 31,  32,  25],
        [ 76,  86,  61],
        [121, 140,  97]])

In [320]:
np.dot(mat1,mat2)

matrix([[ 22,  47,  18],
        [ 61, 110,  51],
        [100, 173,  84]])

In [321]:
np.transpose(mat1)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [322]:
np.trace(mat1)

15

In [323]:
np.linalg.matrix_rank(mat1)

2

In [326]:
np.linalg.det(mat2)

231.00000000000014

In [327]:
np.linalg.inv(mat2)

matrix([[-0.04761905,  0.1991342 , -0.15584416],
        [-0.04761905,  0.01731602,  0.11688312],
        [ 0.23809524, -0.17748918,  0.05194805]])

In [328]:
np.linalg.eig(mat2)

(array([15.62606849+0.j        , -0.31303424+3.83210108j,
        -0.31303424-3.83210108j]),
 matrix([[ 0.53610424+0.j        , -0.32429832-0.50158549j,
          -0.32429832+0.50158549j],
         [ 0.68574932+0.j        , -0.14493498+0.35554923j,
          -0.14493498-0.35554923j],
         [ 0.49228052+0.j        ,  0.70414572+0.j        ,
           0.70414572-0.j        ]]))

In [330]:
a=np.array([2,6]) #Point A(x1,y1)
b=np.array([5,8]) #Point B(x2,y2)

In [333]:
np.sqrt(np.sum(np.square(np.subtract(b,a))))

3.605551275463989